# Generated by Django 3.2 on 2021-05-01 07:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='pdf',
            field=models.FileField(blank=True, upload_to='pdf', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
