# Generated by Django 3.2 on 2021-05-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_pdf_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='pdf_type',
            field=models.IntegerField(choices=[(0, 'simple_basic'), (1, 'deep'), (2, 'short')], verbose_name='pdf_type'),
        ),
    ]
