# Generated by Django 3.2 on 2021-05-02 03:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_pdf_pdf_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=30)),
                ('company_number', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='')),
            ],
        ),
    ]
