# Generated by Django 3.2 on 2021-05-02 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210502_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(blank=True, default='name', max_length=30),
        ),
    ]
