# Generated by Django 3.2 on 2021-05-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210502_0428'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ('company_number',)},
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
