# Generated by Django 3.2 on 2021-05-06 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_ask_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdf',
            options={'ordering': ('company', 'pdf_type', '-regist_date')},
        ),
    ]
